ts:TestingStuff.cpp
	gcc -L/usr/lib -o ts TestingStuff.cpp -lE101

gate:Gate.cpp
	gcc -L/usr/lib -o gate Gate.cpp -lE101
move:movement.cpp
	gcc -L/usr/lib -o move movement.cpp -lE101
run:run.cpp
	gcc -L/usr/lib -o run run.cpp -lE101
countTest:countTest.cpp
	gcc -L/usr/lib -o countTest countTest.cpp -lE101
